// Mocks generated by Mockito 5.4.4 from annotations
// in goldwen_app/test/daily_selection_refresh_ui_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i12;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i2;
import 'package:goldwen_app/core/models/models.dart' as _i4;
import 'package:goldwen_app/core/services/accessibility_service.dart' as _i10;
import 'package:goldwen_app/core/services/performance_cache_service.dart'
    as _i11;
import 'package:goldwen_app/features/matching/providers/matching_provider.dart'
    as _i3;
import 'package:goldwen_app/features/subscription/providers/subscription_provider.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:purchases_flutter/purchases_flutter.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCurve_1 extends _i1.SmartFake implements _i2.Curve {
  _FakeCurve_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MatchingProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatchingProvider extends _i1.Mock implements _i3.MatchingProvider {
  MockMatchingProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.Match> get matches => (super.noSuchMethod(
        Invocation.getter(#matches),
        returnValue: <_i4.Match>[],
      ) as List<_i4.Match>);

  @override
  List<_i4.Profile> get dailyProfiles => (super.noSuchMethod(
        Invocation.getter(#dailyProfiles),
        returnValue: <_i4.Profile>[],
      ) as List<_i4.Profile>);

  @override
  List<String> get selectedProfileIds => (super.noSuchMethod(
        Invocation.getter(#selectedProfileIds),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<_i4.WhoLikedMeItem> get whoLikedMe => (super.noSuchMethod(
        Invocation.getter(#whoLikedMe),
        returnValue: <_i4.WhoLikedMeItem>[],
      ) as List<_i4.WhoLikedMeItem>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingWhoLikedMe => (super.noSuchMethod(
        Invocation.getter(#isLoadingWhoLikedMe),
        returnValue: false,
      ) as bool);

  @override
  bool get hasSubscription => (super.noSuchMethod(
        Invocation.getter(#hasSubscription),
        returnValue: false,
      ) as bool);

  @override
  int get maxSelections => (super.noSuchMethod(
        Invocation.getter(#maxSelections),
        returnValue: 0,
      ) as int);

  @override
  int get remainingSelections => (super.noSuchMethod(
        Invocation.getter(#remainingSelections),
        returnValue: 0,
      ) as int);

  @override
  bool get canSelectMore => (super.noSuchMethod(
        Invocation.getter(#canSelectMore),
        returnValue: false,
      ) as bool);

  @override
  bool get isSelectionComplete => (super.noSuchMethod(
        Invocation.getter(#isSelectionComplete),
        returnValue: false,
      ) as bool);

  @override
  List<_i4.HistoryItem> get historyItems => (super.noSuchMethod(
        Invocation.getter(#historyItems),
        returnValue: <_i4.HistoryItem>[],
      ) as List<_i4.HistoryItem>);

  @override
  bool get hasMoreHistory => (super.noSuchMethod(
        Invocation.getter(#hasMoreHistory),
        returnValue: false,
      ) as bool);

  @override
  bool get canSeeWhoLikedYou => (super.noSuchMethod(
        Invocation.getter(#canSeeWhoLikedYou),
        returnValue: false,
      ) as bool);

  @override
  bool get canUseAdvancedFilters => (super.noSuchMethod(
        Invocation.getter(#canUseAdvancedFilters),
        returnValue: false,
      ) as bool);

  @override
  bool get hasUnlimitedRewinds => (super.noSuchMethod(
        Invocation.getter(#hasUnlimitedRewinds),
        returnValue: false,
      ) as bool);

  @override
  int get superLikesRemaining => (super.noSuchMethod(
        Invocation.getter(#superLikesRemaining),
        returnValue: 0,
      ) as int);

  @override
  int get boostsRemaining => (super.noSuchMethod(
        Invocation.getter(#boostsRemaining),
        returnValue: 0,
      ) as int);

  @override
  bool get isLoadingAdvancedRecommendations => (super.noSuchMethod(
        Invocation.getter(#isLoadingAdvancedRecommendations),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> loadDailySelection() => (super.noSuchMethod(
        Invocation.method(
          #loadDailySelection,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> initializeNotifications() => (super.noSuchMethod(
        Invocation.method(
          #initializeNotifications,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> scheduleDailyNotificationsWithContext(
          _i2.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleDailyNotificationsWithContext,
          [context],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadMatches({
    int? page = 1,
    int? limit = 20,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMatches,
          [],
          {
            #page: page,
            #limit: limit,
            #status: status,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> selectProfile(
    String? profileId, {
    _i6.SubscriptionProvider? subscriptionProvider,
    String? choice = r'like',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectProfile,
          [profileId],
          {
            #subscriptionProvider: subscriptionProvider,
            #choice: choice,
          },
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<_i4.CompatibilityResult?> getCompatibility(String? profileId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompatibility,
          [profileId],
        ),
        returnValue: _i5.Future<_i4.CompatibilityResult?>.value(),
      ) as _i5.Future<_i4.CompatibilityResult?>);

  @override
  _i5.Future<Map<String, dynamic>?> acceptMatch(
    String? matchId, {
    required bool? accept,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptMatch,
          [matchId],
          {#accept: accept},
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> deleteMatch(String? matchId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMatch,
          [matchId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i4.Match?> getMatchDetails(String? matchId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMatchDetails,
          [matchId],
        ),
        returnValue: _i5.Future<_i4.Match?>.value(),
      ) as _i5.Future<_i4.Match?>);

  @override
  bool isProfileSelected(String? profileId) => (super.noSuchMethod(
        Invocation.method(
          #isProfileSelected,
          [profileId],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool shouldShowNewProfiles() => (super.noSuchMethod(
        Invocation.method(
          #shouldShowNewProfiles,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool hasNewSelectionAvailable() => (super.noSuchMethod(
        Invocation.method(
          #hasNewSelectionAvailable,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  String getNextRefreshCountdown() => (super.noSuchMethod(
        Invocation.method(
          #getNextRefreshCountdown,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getNextRefreshCountdown,
            [],
          ),
        ),
      ) as String);

  @override
  void clearDailySelection() => super.noSuchMethod(
        Invocation.method(
          #clearDailySelection,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshSelectionIfNeeded() => super.noSuchMethod(
        Invocation.method(
          #refreshSelectionIfNeeded,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> loadWeekHistory() => (super.noSuchMethod(
        Invocation.method(
          #loadWeekHistory,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadHistory({
    int? page = 1,
    int? limit = 20,
    String? startDate,
    String? endDate,
    bool? refresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadHistory,
          [],
          {
            #page: page,
            #limit: limit,
            #startDate: startDate,
            #endDate: endDate,
            #refresh: refresh,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadWhoLikedMe() => (super.noSuchMethod(
        Invocation.method(
          #loadWhoLikedMe,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearWhoLikedMe() => super.noSuchMethod(
        Invocation.method(
          #clearWhoLikedMe,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> loadAdvancedRecommendations({
    required String? userId,
    required List<String>? candidateIds,
    Map<String, dynamic>? personalityAnswers,
    Map<String, dynamic>? preferences,
    Map<String, dynamic>? userLocation,
    bool? includeAdvancedScoring = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAdvancedRecommendations,
          [],
          {
            #userId: userId,
            #candidateIds: candidateIds,
            #personalityAnswers: personalityAnswers,
            #preferences: preferences,
            #userLocation: userLocation,
            #includeAdvancedScoring: includeAdvancedScoring,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearAdvancedRecommendations() => super.noSuchMethod(
        Invocation.method(
          #clearAdvancedRecommendations,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SubscriptionProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionProvider extends _i1.Mock
    implements _i6.SubscriptionProvider {
  MockSubscriptionProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.SubscriptionPlan> get plans => (super.noSuchMethod(
        Invocation.getter(#plans),
        returnValue: <_i4.SubscriptionPlan>[],
      ) as List<_i4.SubscriptionPlan>);

  @override
  List<_i4.SubscriptionPlan> get activePlans => (super.noSuchMethod(
        Invocation.getter(#activePlans),
        returnValue: <_i4.SubscriptionPlan>[],
      ) as List<_i4.SubscriptionPlan>);

  @override
  List<_i9.Package> get revenueCatPackages => (super.noSuchMethod(
        Invocation.getter(#revenueCatPackages),
        returnValue: <_i9.Package>[],
      ) as List<_i9.Package>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasActiveSubscription => (super.noSuchMethod(
        Invocation.getter(#hasActiveSubscription),
        returnValue: false,
      ) as bool);

  @override
  bool get hasExpiredSubscription => (super.noSuchMethod(
        Invocation.getter(#hasExpiredSubscription),
        returnValue: false,
      ) as bool);

  @override
  bool get willRenew => (super.noSuchMethod(
        Invocation.getter(#willRenew),
        returnValue: false,
      ) as bool);

  @override
  bool get canSeeWhoLikedYou => (super.noSuchMethod(
        Invocation.getter(#canSeeWhoLikedYou),
        returnValue: false,
      ) as bool);

  @override
  bool get canUseAdvancedFilters => (super.noSuchMethod(
        Invocation.getter(#canUseAdvancedFilters),
        returnValue: false,
      ) as bool);

  @override
  bool get hasUnlimitedRewinds => (super.noSuchMethod(
        Invocation.getter(#hasUnlimitedRewinds),
        returnValue: false,
      ) as bool);

  @override
  int get dailyLikesRemaining => (super.noSuchMethod(
        Invocation.getter(#dailyLikesRemaining),
        returnValue: 0,
      ) as int);

  @override
  int get superLikesRemaining => (super.noSuchMethod(
        Invocation.getter(#superLikesRemaining),
        returnValue: 0,
      ) as int);

  @override
  int get boostsRemaining => (super.noSuchMethod(
        Invocation.getter(#boostsRemaining),
        returnValue: 0,
      ) as int);

  @override
  bool get hasRemainingLikes => (super.noSuchMethod(
        Invocation.getter(#hasRemainingLikes),
        returnValue: false,
      ) as bool);

  @override
  bool get hasRemainingSuperLikes => (super.noSuchMethod(
        Invocation.getter(#hasRemainingSuperLikes),
        returnValue: false,
      ) as bool);

  @override
  bool get hasRemainingBoosts => (super.noSuchMethod(
        Invocation.getter(#hasRemainingBoosts),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> initializeWithUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #initializeWithUser,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadSubscriptionPlans() => (super.noSuchMethod(
        Invocation.method(
          #loadSubscriptionPlans,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadCurrentSubscription() => (super.noSuchMethod(
        Invocation.method(
          #loadCurrentSubscription,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadSubscriptionUsage() => (super.noSuchMethod(
        Invocation.method(
          #loadSubscriptionUsage,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> purchaseSubscription({
    required String? planId,
    required String? platform,
    required String? receiptData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #purchaseSubscription,
          [],
          {
            #planId: planId,
            #platform: platform,
            #receiptData: receiptData,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> cancelSubscription() => (super.noSuchMethod(
        Invocation.method(
          #cancelSubscription,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> restoreSubscription() => (super.noSuchMethod(
        Invocation.method(
          #restoreSubscription,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i4.SubscriptionPlan? getPlanById(String? planId) =>
      (super.noSuchMethod(Invocation.method(
        #getPlanById,
        [planId],
      )) as _i4.SubscriptionPlan?);

  @override
  _i5.Future<void> refreshAll() => (super.noSuchMethod(
        Invocation.method(
          #refreshAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AccessibilityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccessibilityService extends _i1.Mock
    implements _i10.AccessibilityService {
  MockAccessibilityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.AccessibilityFontSize get fontSize => (super.noSuchMethod(
        Invocation.getter(#fontSize),
        returnValue: _i10.AccessibilityFontSize.small,
      ) as _i10.AccessibilityFontSize);

  @override
  bool get highContrast => (super.noSuchMethod(
        Invocation.getter(#highContrast),
        returnValue: false,
      ) as bool);

  @override
  bool get reducedMotion => (super.noSuchMethod(
        Invocation.getter(#reducedMotion),
        returnValue: false,
      ) as bool);

  @override
  bool get screenReaderEnabled => (super.noSuchMethod(
        Invocation.getter(#screenReaderEnabled),
        returnValue: false,
      ) as bool);

  @override
  double get textScaleFactor => (super.noSuchMethod(
        Invocation.getter(#textScaleFactor),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isAccessibilityEnabled => (super.noSuchMethod(
        Invocation.getter(#isAccessibilityEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setFontSize(_i10.AccessibilityFontSize? fontSize) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFontSize,
          [fontSize],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setHighContrast(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setHighContrast,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setReducedMotion(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setReducedMotion,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setScreenReaderEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setScreenReaderEnabled,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Duration getAnimationDuration(Duration? defaultDuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnimationDuration,
          [defaultDuration],
        ),
        returnValue: _FakeDuration_0(
          this,
          Invocation.method(
            #getAnimationDuration,
            [defaultDuration],
          ),
        ),
      ) as Duration);

  @override
  _i2.Curve getAnimationCurve(_i2.Curve? defaultCurve) => (super.noSuchMethod(
        Invocation.method(
          #getAnimationCurve,
          [defaultCurve],
        ),
        returnValue: _FakeCurve_1(
          this,
          Invocation.method(
            #getAnimationCurve,
            [defaultCurve],
          ),
        ),
      ) as _i2.Curve);

  @override
  Map<String, dynamic> exportSettings() => (super.noSuchMethod(
        Invocation.method(
          #exportSettings,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i5.Future<void> importSettings(Map<String, dynamic>? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #importSettings,
          [settings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PerformanceCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPerformanceCacheService extends _i1.Mock
    implements _i11.PerformanceCacheService {
  MockPerformanceCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cacheData(
    String? key,
    dynamic data, {
    Duration? expiry,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheData,
          [
            key,
            data,
          ],
          {#expiry: expiry},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  T? getCachedData<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #getCachedData,
        [key],
      )) as T?);

  @override
  _i5.Future<void> cacheImage(
    String? url,
    _i12.Uint8List? imageData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheImage,
          [
            url,
            imageData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i12.Uint8List? getCachedImage(String? url) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedImage,
        [url],
      )) as _i12.Uint8List?);

  @override
  _i5.Future<_i12.Uint8List?> loadImageWithCache(
    String? url, {
    Map<String, String>? headers,
    dynamic Function(
      int,
      int,
    )? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadImageWithCache,
          [url],
          {
            #headers: headers,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i5.Future<_i12.Uint8List?>.value(),
      ) as _i5.Future<_i12.Uint8List?>);

  @override
  _i5.Future<void> cacheProfile(
    String? profileId,
    Map<String, dynamic>? profileData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProfile,
          [
            profileId,
            profileData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, dynamic>? getCachedProfile(String? profileId) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedProfile,
        [profileId],
      )) as Map<String, dynamic>?);

  @override
  _i5.Future<void> preloadProfiles(
    List<String>? profileIds, {
    required _i5.Future<Map<String, dynamic>?> Function(String)? loadFunction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #preloadProfiles,
          [profileIds],
          {#loadFunction: loadFunction},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllCaches() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCaches,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, dynamic> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
