include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Styling
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_single_quotes: true
    avoid_unnecessary_containers: true
    prefer_const_declarations: true
    
    # Error prone
    close_sinks: true
    cancel_subscriptions: true
    
    # Pub
    sort_pub_dependencies: true