name: goldwen_app
description: A premium dating app that prioritizes quality over quantity connections.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^16.2.0
  
  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Authentication
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.1
  google_sign_in: 6.1.5
  sign_in_with_apple: ^7.0.1
  
  # Backend & API
  http: ^1.1.0
  dio: ^5.3.3
  web_socket_channel: ^3.0.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notifications
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  
  # Image Handling
  image_picker: ^1.0.4
  image_cropper: ^10.0.0+1
  flutter_image_compress: ^2.1.0
  
  # File Handling
  path_provider: ^2.1.1
  share_plus: ^10.1.4
  file_picker: ^8.1.6
  
  # Media Playback
  video_player: ^2.9.2
  audioplayers: ^6.1.0
  
  # Location Services
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  
  # UI Utilities
  shimmer: ^3.0.0
  lottie: ^3.3.1
  
  # Subscriptions
  in_app_purchase: ^3.1.11
  
  # Analytics
  mixpanel_flutter: ^2.3.1
  purchases_flutter: ^9.6.2
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.2.1
  emoji_picker_flutter: ^4.3.0
  crypto: ^3.0.3
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    
  fonts:
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300